#ifndef SE_GLOBALS_H
#define SE_GLOBALS_H

#include "shared.h"

#define USE_GLFW 1
#define VSYNC 0
#define FULL_SCREEN 0
#define SCREEN_ASPECT 10.0f / 16.0f
#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT (int)((float)WINDOW_WIDTH * SCREEN_ASPECT)

#define NEAR_CLIPPING_RANGE 1.0
#define FAR_CLIPPPING_RANGE 10000.0

#define OK 0

#define DEBUG_LOG 0

#define DELTA_TIME 1.0f / 100.0f

#define LOCATION_VERTEX 0
#define LOCATION_NORMAL 1
#define LOCATION_UV 2
#define LOCATION_TANGENT 3

#define BUFFER_VERTEX 0
#define BUFFER_NORMAL 1
#define BUFFER_EBO 2
#define BUFFER_VAO 3
#define BUFFER_UV 4
#define BUFFER_INDEX_COUNT 5
#define BUFFER_TANGENT 6

#define SHADER_MODEL_MATRIX 0
#define SHADER_VIEW_MATRIX 1
#define SHADER_MODELVIEW_MATRIX 2
#define SHADER_PROJ_MATRIX 3
#define SHADER_MVP 4
#define SHADER_NORMAL_MATRIX 5
#define SHADER_TEXTURE_DIFFUSE 6
#define SHADER_TEXTURE_BUMP 7
#define SHADER_TEXTURE_HEIGHT 8
#define SHADER_LIGHT_POSITION 9
#define SHADER_LIGHT_LD 10
#define SHADER_LIGHT_LS 11
#define SHADER_LIGHT_LA 12
#define SHADER_FONT_COORDS 13
#define SHADER_FONT_COLOR 14
#define SHADER_SPACEOBJECT_TYPE 15
#define SHADER_DELTA 16

#define MAX_ATTRIBUTES (8192)
#define MAX_TRIANGLE_ATTRIBUTES (32768)
#define BUFFERSIZE 256

#define TEXTURE_TYPE_UNKNOWN 0x0
#define TEXTURE_GL_RGB 0x1907
#define TEXTURE_GL_RGBA 0x1908

#endif // !GLOBALS_H
